# Generated by Django 5.0.6 on 2024-06-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(max_length=50)),
                ('ejercicio', models.PositiveBigIntegerField()),
                ('mes', models.PositiveBigIntegerField()),
                ('dia', models.PositiveBigIntegerField()),
                ('hora', models.PositiveBigIntegerField()),
                ('servicio', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=50)),
                ('disponible', models.PositiveBigIntegerField()),
                ('habilitado', models.PositiveBigIntegerField()),
                ('instalado', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'Infraestructura',
                'verbose_name_plural': 'Infraestructura',
            },
        ),
    ]
