# Generated by Django 5.0.6 on 2024-06-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra',
            name='dia',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='infra',
            name='disponible',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='infra',
            name='ejercicio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='infra',
            name='habilitado',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='infra',
            name='hora',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='infra',
            name='instalado',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='infra',
            name='mes',
            field=models.PositiveIntegerField(),
        ),
    ]
