# Generated by Django 5.0.6 on 2024-06-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_alter_infra_dia_alter_infra_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='filiales',
            fields=[
                ('id_filial', models.IntegerField(primary_key=True, serialize=False)),
                ('filial', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiales',
            },
        ),
    ]
