# Generated by Django 5.0.6 on 2024-06-22 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_filiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infra',
            name='filial',
        ),
        migrations.AddField(
            model_name='infra',
            name='id_filial',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='infra.filiales'),
        ),
    ]
