# Generated by Django 5.0.6 on 2024-06-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_remove_infra_filial_infra_id_filial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filiales',
            old_name='filial',
            new_name='nombre_filial',
        ),
    ]
