# Generated by Django 5.0.6 on 2024-06-22 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_rename_filial_filiales_nombre_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra',
            name='id_filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.filiales'),
        ),
    ]
