# Generated by Django 5.0.6 on 2024-06-23 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0006_alter_infra_id_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id_unidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'unidad',
                'verbose_name_plural': 'unidades',
            },
        ),
        migrations.RemoveField(
            model_name='infra',
            name='servicio',
        ),
        migrations.AddField(
            model_name='infra',
            name='id_servicio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='infra.servicios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infra',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.unidades'),
        ),
    ]
