# Generated by Django 5.0.6 on 2024-06-30 22:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0007_servicios_unidades_remove_infra_servicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infra',
            old_name='unidad',
            new_name='id_unidad',
        ),
        migrations.AlterField(
            model_name='infra',
            name='mes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField()),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('actividad', models.PositiveIntegerField()),
                ('id_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.filiales')),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.unidades')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividad',
            },
        ),
    ]
