# Generated by Django 5.0.6 on 2024-06-30 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0008_rename_unidad_infra_id_unidad_alter_infra_mes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra',
            name='hora',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
