# Generated by Django 5.0.6 on 2024-07-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0012_alter_actividad_ejercicio_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.UniqueConstraint(fields=('id_filial', 'ejercicio', 'mes', 'id_unidad'), name='unique_actividad_combination'),
        ),
        migrations.AddConstraint(
            model_name='infra',
            constraint=models.UniqueConstraint(fields=('id_filial', 'ejercicio', 'mes', 'dia', 'hora', 'id_unidad'), name='unique_infra_combination'),
        ),
    ]
