# Generated by Django 5.0.6 on 2024-07-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0013_actividad_unique_actividad_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='mes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='infra',
            name='hora',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='infra',
            name='mes',
            field=models.PositiveIntegerField(),
        ),
    ]
