# Generated by Django 5.0.6 on 2024-07-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0014_alter_actividad_mes_alter_infra_hora_alter_infra_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infra',
            name='disponible',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='infra',
            name='habilitado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='infra',
            name='instalado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
